// <auto-generated />
namespace BITCollege_EU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_final_migration_stored : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_final_migration_stored));
        
        string IMigrationMetadata.Id
        {
            get { return "202102030241239_add_final_migration_stored"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
