// <auto-generated />
namespace BITCollege_EU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_StudentCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_StudentCard));
        
        string IMigrationMetadata.Id
        {
            get { return "202102021704388_added_StudentCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
